openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-aws-rds-postgresql
components:
  schemas:
    variables:
      required:
      - infrastructure
      type: object
      properties:
        context:
          title: Context
          type: object
          description: |
            Receive contextual information. When Walrus deploys, Walrus will inject specific contextual information into this field.

            Examples:
            ```
            context:
              project:
                name: string
                id: string
              environment:
                name: string
                id: string
              resource:
                name: string
                id: string
            ```
          default: {}
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            hidden: true
            order: 1
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.

            Examples:
            ```
            infrastructure:
              vpc_id: string                  # the ID of the VPC where the PostgreSQL service applies
              kms_key_id: sting,optional      # the ID of the KMS key which to encrypt the PostgreSQL data
              domain_suffix: string,optional  # a private DNS namespace of the CloudMap where to register the applied PostgreSQL service
            ```
          required:
          - vpc_id
          properties:
            domain_suffix:
              description: |
                Specify the domain suffix of the CloudMap. The domain suffix must be a valid DNS name.
              title: Domain Suffix
              type: string
              x-walrus-ui:
                order: 3
            kms_key_id:
              description: |
                Specify the KMS key ID which to encrypt the PostgreSQL data. If not specified, the PostgreSQL data will not be encrypted.
              title: Kms Key Id
              type: string
              x-walrus-ui:
                order: 2
            vpc_id:
              description: |
                Specify the ID of the VPC where the PostgreSQL service applies.
              title: Vpc Id
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 2
        architecture:
          title: Architecture
          type: string
          description: |
            Specify the deployment architecture, select from standalone or replication.
          default: standalone
          enum:
          - standalone
          - replication
          x-walrus-ui:
            group: Basic
            order: 3
        replication_readonly_replicas:
          title: Replication Readonly Replicas
          type: number
          description: |
            Specify the number of read-only replicas under the replication deployment.
          default: 1
          enum:
          - 1
          - 3
          - 5
          x-walrus-ui:
            group: Basic
            order: 4
            showIf: architecture=replication
        engine_version:
          title: Engine Version
          type: string
          description: |
            Specify the deployment engine version, select from https://docs.aws.amazon.com/AmazonRDS/latest/PostgreSQLReleaseNotes/postgresql-release-calendar.html#Release.Calendar.
          default: "13"
          enum:
          - "13"
          - "14"
          - "15"
          x-walrus-ui:
            group: Basic
            order: 5
        engine_parameters:
          title: Engine Parameters
          type: array
          description: |
            Specify the deployment engine parameters, select for https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.Parameters.html.
          items:
            properties:
              name:
                title: Name
                type: string
              value:
                title: Value
                type: string
            required:
            - name
            - value
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            hidden: true
            order: 6
        database:
          title: Database
          type: string
          description: |
            Specify the database name.
          default: mydb
          x-walrus-ui:
            group: Basic
            order: 7
        username:
          title: Username
          type: string
          description: |
            Specify the account username.
          default: rdsuser
          x-walrus-ui:
            group: Basic
            order: 8
        password:
          title: Password
          type: string
          description: |
            Specify the account password, ref to https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.Constraints.
            If not specified, it will generate a random password.
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 9
        resources:
          title: Resources
          type: object
          description: |
            Specify the computing resources.

            Examples:
            ```
            resources:
              class: string, optional         # https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html#Concepts.DBInstanceClass.Summary
            ```
          default:
            class: db.t3.medium
          properties:
            class:
              description: |
                Specify the computing resources. See https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html#Concepts.DBInstanceClass.Summary.
              default: db.t3.medium
              title: Class
              type: string
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 10
        storage:
          title: Storage
          type: object
          description: |
            Specify the storage resources.

            Examples:
            ```
            storage:
              class: string, optional        # https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html
              size: number, optional         # in megabyte
            ```
          default:
            class: gp2
            size: 20480
          properties:
            class:
              description: |
                Specify the storage class. See https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html.
              default: gp2
              title: Class
              type: string
              x-walrus-ui:
                order: 1
            size:
              description: |
                Specify the storage size. Unit is megabyte.
              default: 20480
              title: Size(MiB)
              type: number
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 11
